# Generated by Django 4.2.2 on 2023-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathawayUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=35)),
                ('contactnumber', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('isactive', models.IntegerField(default=0)),
                ('isverified', models.IntegerField(default=0)),
            ],
        ),
    ]
