# Generated by Django 4.2.2 on 2023-06-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathaway', '0004_chargingstation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingStation',
        ),
    ]
