# Generated by Django 4.2.2 on 2023-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathaway', '0006_chargingstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
