# Generated by Django 4.2.2 on 2023-06-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathaway', '0007_alter_chargingstation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
